### PR TITLE
feature: Dockerfile

### PR DESCRIPTION
**Pull request by icirellik**
Adds a basic Dockerfile for those that want to test in a secure
environment.

### CODE REVIEW

**Comment by DakkJaniels** [comment]
commits with new features go against development, only development (except for hotfixes) is committed to master. Can you please change this?

**Comment by unapproachable** [comment]
@icirellik I'm happy to commit this, but is there any chance you could include additional information in a readme of some sort so we can point users to something?  Everyone who knows Docker will be fine, but this will lead to additional usage questions from the community about how they too can be a cool kid and run a Docker version so they can run 67 instances.

**Comment by icirellik** [comment]
Sorry, I was hoping to update this week and ran out of time. I'm running it in Docker locally and will update it in the future. Don't get me wrong but I don't trust anyone with access to my Amazon account 💖

**Comment by wes1993** [comment]
Hello, did someone have found a way to create the container after the image was built?

I have tried but the container stop after 2 sec with error code 0

Thanks a lot
Stefano

**Pull request closed without merging**
