### PR TITLE
Upgrade bestbuy to support json mode with multiple SKUs using the same concept as amazon_config.json

### PR DESCRIPTION
**Pull request by cy11100**

### CODE REVIEW

**Comment by unapproachable** [comment]
This looks like a lot of heavy lifting in spawning Chrome instead of bestbuy API which is lighter weight and takes less resources.  It's also creating new profiles instead of leveraging the "default browser" that the current version does, which allows the script to use the logged in state of the user to add to cart and checkout without needing Selenium, etc.  Maybe multiple skus is a first step, and then upgrading to a config file appropriate for this set of APIs?

**Comment by cy11100** [comment]
The "heavy lifting" (i.e. the actual refreshing) still uses the bestbuy API. This is unchanged from the existing code. 

The rationale behind creating a new profile and using that profile to launch the add to cart is twofold: 

1: It guarantees that you will be logged in since it checks that when starting a session, as opposed to the system browser session which has no such guarantee. 

2: It presents a better unified environment which works exactly like the Amazon merchant. Currently, there is no indication that you need to be logged in for your system browser session, which could waste precious seconds if the user did not perform the login in advance, or if they closed their browser and the session cookie expired. 

It's possible to revert that to the previous functionality, but IMO the drawbacks outweigh the benefits.

**Comment by unapproachable** [comment]
By Heavy Lifting, I am speaking specifically about spawning Selenium/Chrome.  It's not necessary for the current functionality and without the added benefits of progressing into checkout, it's a lot to add to the currently low-featured script.  If someone can implement the Selenium portion of it, I'm all for it.  I just wasn't sure we should do all that 'extra' work when we have no downstream functionality.

Also, full disclosure, I implemented the multiple SKU version in parallel to your development effort, so I'm sort of biased towards my code versus yours :-)  But again, I'm mostly just lobbying for not doing the Selenium stuff if we don't get further downstream on the add to cart (which is currently hard because of the interactive nature of the Best Buy checkout).

https://github.com/Hari-Nagarajan/nvidia-bot/pull/370

**Comment by cy11100** [comment]
Makes perfect sense. I feel likewise, so let's just see which one the maintainer finds better. Having a unified config system definitely beats trying to implement multiple sku values IMO. It's trivially easy to merge them into a single config file if so desired too.

**Comment by cy11100** [comment]
Closing this PR because Bestbuy API no longer updates the in-stock status accurately. Add to cart queue was showing for over 30 minutes while the API continuously showed "Coming soon" for the 3060Ti FE SKU.

**Pull request closed without merging**
