### PR TITLE
Tunes the volume down on the frenzy alarm notification

### PR DESCRIPTION
**Pull request by HeyBanditoz**
### Reason for change
I was playing a game of League of Legends and through my headphones was the loudest ear-piercing noise I've ever heard. This PR tunes the amplification from Audacity of the frenzy alarm notification down.

Before:
audacity_eDkMqbGa56
After:
audacity_39PvW0GayV

### CODE REVIEW

**Comment by HeyBanditoz** [comment]
Stale? :(

**Review by timbru31 — APPROVED** [review]
Ouch, I agree this is WAY too loud.

**Comment by DakkJaniels** [comment]
Can we keep the old file, in case someone isn't wearing headphones and wants an earsplitting noise? I'm ok renaming the existing file to a different name so the ear-friendly file is default. Sorry, I was going to try and look into changing the volume of the audio, but never got around to it.

**Comment by HeyBanditoz** [comment]
I'll do this, yeah. Give me a few minutes.

**Comment by HeyBanditoz** [comment]
Force pushed. Should be good to go now.

**Review by DakkJaniels — APPROVED** [review]

**Pull request merged**
