### PR TITLE
[WIP] Docker support

### PR DESCRIPTION
**Pull request by luigi311**
Add dockerfile that will generate a docker image and allow you to run the application via the docker image. I have tested and confirmed that bestbuy works, amazon requires the --headless flag to work and doesnt seem to progress passed 
```
POST http://127.0.0.1:42861/session/8e03bdafa0a9d2c7aab6d15713c8169f/url {"url": "https://www.amazon.com/"}
```
seems to be an issue with headless.
Signed-off-by: Luis Garcia <luigi311.lg@gmail.com>

### CODE REVIEW

**Comment by luigi311** [comment]
We might want to grab the version of chrome that is installed and replace the chromedriver-py version in pipfile to the matching version but not sure if you are ok with this method. If we do go that route we can instead use chromium.

**Comment by luigi311** [comment]
This current outputs at the end
```
ERROR 'NoneType' object has no attribute 'props'
2020-11-05 22:39:38 8947f52920fe nvidia-bot[1] WARNING Error playing notification sound. Disabling local audio notifications.
```
The ERROR i am unsure how to fix as online i can only find to install gstreamer1.0-gtk3 which i already have. As for the warning is there a way to turn the audio notification off?

**Comment by jdamour98** [comment]
@luigi311 Is this working apart from the notification error? Will happily test it out :)

**Comment by luigi311** [comment]
Closing as someone else is working on docker support and was able to progress more than i was.

**Comment by pdzurina** [comment]
@luigi311 who is doing it and where? I can't find it.

**Comment by c0m3d1an** [comment]
I'm guessing it's [Hari-Nagarajan](https://github.com/Hari-Nagarajan/fairgame), as that's the pull requester in this thread, but that's just a guess.

**Comment by c0m3d1an** [comment]
I'm guessing it's [luigi311](https://github.com/luigi311/nvidia-bot), since he's the pull-requester on this thread.

**Comment by c0m3d1an** [comment]
Here maybe?  [Dockerfile](https://raw.githubusercontent.com/luigi311/nvidia-bot/master/Dockerfile)

**Comment by luigi311** [comment]
@pdzurina c0m3d1an Development was happening by a discord user. Not sure if they ever made any progress either due to the same headless issue. If the headless issue was fixed i don't mind reopening this and merging my docker script in if it works

**Comment by gtrak** [comment]
FYI you could do a Xvfb non-headless thing in docker like this:
https://github.com/seanpianka/docker-python-xvfb-selenium-chrome-firefox

**Pull request closed without merging**
