### PR TITLE
Support running multiple instances

### PR DESCRIPTION
**Pull request by ItsCalebJones**
This seems to work well for me locally, don't seem to be any breaking changes.

Two small caveats:

1) Any new instance needs to be tested `--test` or otherwise configured with one-click setup as it creates a new Chrome profile anytime the `--instance_name` is unique.
2) All logs are still logged together into the same log files.

### CODE REVIEW

**Comment by DakkJaniels** [comment]
No:
image

**Comment by ItsCalebJones** [comment]
Lmao - right you didnt support it which is why I looked into its feasibility - it took less then an hour to implement, its a no brainer rather then spinning up multiple VMs/Docker containers.

**Comment by DakkJaniels** [comment]
It's not that we couldn't, the point was to not make it super easy for every single person to run thousands of bots.

**Comment by ItsCalebJones** [comment]
HA - wow, that excuse is almost worse then a few technical ones I could think of. The entire point of 'FairGame' is to level the playing field for the botters that DO run thousands of bots. Every person will be limited by their hardware, unless they have access and knowledge of AWS - which in that case - i've demonstrated you've already made it easy enough to make a few small changes to then make thousands of bots. 

Instead now you're making a philosophical argument that goes counter to the entire premise of this repo - if I get a GPU tomorrow, I turn this off.  The faster I get one vs a botter the faster the next person gets one...?

**Comment by DakkJaniels** [comment]
Then publicize your own fork and support all the people that want to DDoS Amazon.

**Comment by DakkJaniels** [comment]
How much time are you spending dealing with people in Discord who run a bunch of bots at a low (or zero) delay and then complain about how they are getting banned by Amazon? Why would I want to make it even easier for people to run a bunch of bots so we have to deal with even more people who have no idea what they are doing asking why they keep getting banned because they are making hundreds of requests to Amazon per second?

At least if we are going to make an obscene number of requests to Amazon during monitoring, it needs to be supported by rotating proxies. I also wouldn't mind seeing some sort of increased level of checkout requests when something does come into stock, to try and push through the checkout process. Spinning up a bunch of bots running on selenium with no proxies seems like a waste of time and bandwidth though.

**Pull request closed without merging**
