### PR TITLE
allow for specifying amazon configuration file at command line

### PR DESCRIPTION
**Pull request by briandilley**

### CODE REVIEW

**Review by worst-mod-confirmed — DISMISSED** [review]

**Review by worst-mod-confirmed — COMMENTED** [review]
This could be a bad idea. We stuck to one directory per instance because in the early days it would fill peoples drives up if the script didnt exit cleanly, not sure we want to go through that again.

**Comment by unapproachable** [comment]
This patch would gracefully solve the ability to run multiple instances of the 'amazon' script concurrently without concern for the webdriver failing to spawn due to a profile conflict.  It also allows segmentation of inquiries once the delay time gets pushed down to the configuration file rather than being hard coded.

**Comment by worst-mod-confirmed** [comment]
The issue still remains that each instance will create a ~1gb profile directory that isnt being cleaned up on exit. This shouldn't be merged until some cleanup code is added to verify that were not just writing a new directory everytime the script launches.

**Comment by unapproachable** [comment]
Isn't the cleanup the job of Selenium and the driver?  I'm about 3 days into Python, so I'm not exactly sure how to correctly shut down the driver on exit, but it seems that it cleans up after itself if it isn't terminated abruptly.  Of all my profile directories that I've created, only one is greater than 150 MB and that's entirely the cache directory within the Profile.  Is there a shutdown hook in Python that can be used to ensure the webdriver is closed cleanly?  That seems to mitigate a lot of the space concern.  That's obviously another coding effort that would precede this PR.  Deleting profiles on exit will certainly cause more problems with the current smile.amazon.com login procedure than it solves, since it would require manually logging in every time and restarting the bot.

**Comment by worst-mod-confirmed** [comment]
That may be the intended functionality, but it doesn't appear to happen. Confirmed with a clean shutdown, the directory persisted and is at ~725 mb for the single profile. It would appear that the expectation is that driver.quit() will cleanup when called, but that doesnt currently happen. We would need to return the object back to the handler in cli to call the quit when ctrl-c is pressed. No where else in the code do we do this though so there's some legwork that would need to be done.

**Comment by briandilley** [comment]
I ran this with 3 instances running yesterday and machine ran out of system
memory (not HD space) - I have 128GB ram too, so I suspect there is a leak
somewhere. That said, it worked fine for a few hours before that happened.

**Comment by worst-mod-confirmed** [comment]
Interesting, I ran it for 4 days on 6 gig and never had an issue. Can you try and replicate and see what is eating ram?

**Comment by briandilley** [comment]
I'll try again. I suspect it was the driver + chrome though given that the
scripts had times out and crashed.

**Comment by DakkJaniels** [comment]
stale

**Pull request closed without merging**
