### PR TITLE
Change N param to be dependent on system memory or at most 2^20

### PR DESCRIPTION
**Pull request by andrewso726**
Updates scrypt() to use a value that is based off of available system memory.  Right now it is hard-coded to 2^20

### CODE REVIEW

**Review by DakkJaniels — COMMENTED** [review]
If this is based off of available memory, and available memory significantly changes between runs, would it be unable to decrypt the file?

**Comment by DakkJaniels** [comment]
Or maybe I don't understand what total vs. available means?

**Comment by andrewso726** [comment]
> ~Or maybe I don't understand what total vs. available means?~
> Never mind:
> image
> 
> Would it be better to use total?

I believe if you used total and the system have no swap allocated, it'll just error out again.  In most cases, it should use 2^20, which most systems would have.

**Comment by DakkJaniels** [comment]
I don't mean use to total as your number, but base the calculation off of total. Maybe it is half of that, or a quarter, but total physical memory seems less likely to change than available.

**Comment by andrewso726** [comment]
> I don't mean use to total as your number, but base the calculation off of total. Maybe it is half of that, or a quarter, but total physical memory seems less likely to change than available.

Very good point, memory would fluxuate and turning off a program may cause the system not restart properly.  I'll make that change.

**Comment by DakkJaniels** [comment]
Sorry, I thought this was against the development branch, I tried to change what it's pointing to, but then it wants to adjust a bunch of other files too. Can you submit the modifications against development instead? If not, I can make a new PR and give you the credit for it.

**Comment by andrewso726** [comment]
I'll make a new PR

**Pull request closed without merging**
